apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: test
  namespace: kube-system
  labels:
    test: test
spec:
  template:
    metadata:
      labels:
        test: test
    spec:
      serviceAccountName: default
      containers:
      - name: test
        image: ubuntu:18.04
        args: [/bin/sh, -c, 'sleep infinity']
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers